### ISSUE TITLE
I want to add japanese localization to the Bozjan Front FATES

### ISSUE THREAD

**Issue by BDtetra** [purutu/ACT.DFAssist#13]
I can either send in the file via twitter/discord/whatever or i can edit the file directly if that's ok with repository access

**Comment by purutu** [comment]
If you don't mind, can you leave comment here only bozja part?
Or,  please send me your data by discord (ID: Wanderer#6196)

Thank you!

**Comment by purutu** [comment]
Thanks a lot!
