### ISSUE TITLE
Korean server support

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [purutu/ACT.DFAssist#16]
한국 서버에서도 사용할 수 있게 패치하고 싶은데 혹시 opcode 알아내는 법 적혀있는 곳이라던가 있나요?

```javascript
			new GamePacket
			{
				Version = "Current",
				OpFate = 0x02C8,
				FateIndex = 0x35,
				OpDuty = 0x03DB,
				DutyRoulette = 8,
				DutyInstance = 12,
				OpMatch = 0x02C4,
				MatchRoulette = 2,
				MatchInstance = 20,
				OpInstance = 0x010B,
				CriticalEngagement = 0x0143,
			},
```

**Comment by purutu** [comment]
아... 데이터로 역으로 유추하는 프로그램을 만들어서 패치때마다 돌려보고 있습니다.
정확하지 않아서 운나쁘면 한시간 이상 돌려봐야 하는 문제가 있습니다..

편하게 알 수 있는 법이 있다면 좋겠습니다

**Comment by purutu** [comment]
![image](https://user-images.githubusercontent.com/47320226/99784228-d7a88d80-2b5e-11eb-94d3-f620674b69ed.png)
이런건데, 원시코드가 지저분해서... 😫

한국 어카운트 갖고 있으니 들어가서 동작하나 확인해보겠습니다

**Comment by Jaehyuk-Lee** [comment]
아... 저도 DFAssist 변형해서 데이터 들어올 때마다 특정 지역에 돌발임무 ID 데이터가 들어오는지 체크하는 방식으로 했었는데
언제부터인가 제대로 안되서 그냥 손놓고 있었거든요... 같은 방식으로 글섭은 잡히는데 한섭은 안잡혀서 그냥 포기했었는데...

**Comment by purutu** [comment]
한국 서버 코드 입니다
인스턴스는 시간상 못찾겠습니다. 정량제가 얼마 안남아서! 😭

OpFate = 0x0200,
FateIndex = 0x35,
OpDuty = 0x0156,
DutyRoulette = 8,
DutyInstance = 12,
OpMatch = 0x0242,
MatchRoulette = 2,
MatchInstance = 20,
OpInstance = 0,
CriticalEngagement = 0,

**Comment by purutu** [comment]
![image](https://user-images.githubusercontent.com/47320226/99789831-8b614b80-2b66-11eb-889c-f04fdec0be18.png)
잘되는거 같습니다

**Comment by Jaehyuk-Lee** [comment]
잘 되네요. 일단 좀 더 알아보고 닫을게요.

**Comment by purutu** [comment]
이 안건은 일단 닫겠습니다

**Comment by Jaehyuk-Lee** [comment]
아 네 깜빡했네요
