### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by Wildman48** [purutu/ACT.DFAssist#2]
Hello! This is my first time trying this type of plug in and after being installed it seems that it should be in working order, but when ever I zone anywhere the overlay flashes red and even plays the sound (Shows Unknown Zone with numbers). When it's queued up for a roulette and a dungeon pops up it does nothing. This is the US version 5.18 and the files are unblocked. No other errors in the logs and seems like it should work.

**Comment by purutu** [comment]
Happy new year @Wildman48 !
The problem you experienced was that the plugin didn't support 5.18 game update.
I just updated a new release of support 5.18 game update, I want you to try it.

https://github.com/purutu/ACT.DFAssist/releases

**Comment by Wildman48** [comment]
@purutu  Thank you very much for the quick fix and reply! I tried the new version and it's working correctly!
