### ISSUE TITLE
Some questiona about 5.1 client of China and Korea version

### ISSUE THREAD

**Issue by qiulonglideziyou** [purutu/ACT.DFAssist#5]
Hello!How can I use this plugin on 5.1 client of China and Korea version?I just know that 5.1 DX11 client's memory address is 1BF9B20.

**Comment by purutu** [comment]
I tested the Korean client 2 week ago, and I could confirmed that this plugin working well.
Korean client also worked well except for duty roulette because its obfuscated packets

Please let me know if you get any problem using this plugin :)
